### ISSUE TITLE
Uncaught error thrown by session.send

### ISSUE THREAD

**Issue by ryanbmilbourne** [spectcl/spectcl#135]
## Description of the bad behavor
`session.send` will throw when there are errors writing to the spawned session.

## Version of `spectcl` showing said bad behavior
0.6.2

## Description of how to reproduce the problem
Using spectcl with many telnet sessions (>25) can reproduce the issue.  Our tool depends on spectcl to interact with many devices, including sending `exit` to the telnet sessions in question to end the session.

Spectcl has crashed! 
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: This socket is closed.
    at Socket._writeGeneric (net.js:656:19)
    at Socket._write (net.js:709:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Socket.Writable.write (_stream_writable.js:217:11)
    at Socket.write (net.js:634:40)
    at Spectcl.send (/home/rmilbourne/ut-tools/node_modules/spectcl/lib/spectcl.js:480:22)
    at /home/rmilbourne/ut-tools/lib/ut-tools.js:481:29
    at iterate (/home/rmilbourne/ut-tools/node_modules/async/lib/async.js:262:13)
    at /home/rmilbourne/ut-tools/node_modules/async/lib/async.js:274:29
```

This is one example.  Others exceptions include EPIPE.

## Description of the expected behavior
Spectcl should gracefully handle the stream error, rather than throwing.

**Comment by gcochard** [comment]
In which version(s) of node does this manifest?

**Comment by ryanbmilbourne** [comment]
v0.12.7.
